[package]
edition = "2021"
name = "threte"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = "0.1.37"

[dev-dependencies]
env_logger = "0.10.0"
test-log = "0.2.11"
